apps/funcionarios/urls.py
from django.urls import path
from .views import FuncionariosList, FuncionarioEdit, FuncionarioDelete, FuncionarioNovo, relatorio_funcionarios, Pdf



urlpatterns = [
    path('', FuncionariosList.as_view(), name='list_funcionarios'),
    path('novo/', FuncionarioNovo.as_view(), name='create_funcionario'),
    path('editar/<int:pk>/', FuncionarioEdit.as_view(), name='update_funcionario'),
    path('delete/<int:pk>/', FuncionarioDelete.as_view(), name='delete_fucionario'),
    path('relatorio_funcionarios', relatorio_funcionarios, name='relatorio_funcionarios'),
    path('relatorio_funcionarios_html', Pdf.as_view(), name='relatorio_funcionarios_html'),

]

gestao_rh/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls')),
    path('funcionarios/', include('apps.funcionarios.urls')),
    path('departamentos/', include('apps.departamentos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('empresa/', include('apps.empresas.urls')),
    path('documentos/', include('apps.documentos.urls')),
    path('horas-extras/', include('apps.registro_hora_extra.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/documentos/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario


class Documento(models.Model):
    descricao = models.CharField(max_length=100)
    pertence = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    arquivo = models.FileField(upload_to='documentos')

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.pertence.id])

    def __str__(self):
        return self.descricao

apps/funcionarios/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

from apps.departamentos.models import Departamento
from apps.empresas.models import Empresas


class Funcionario(models.Model):
    nome = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    departamentos = models.ManyToManyField(Departamento)
    empresa = models.ForeignKey(Empresas, on_delete=models.PROTECT, null=True, blank=True)
    de_ferias = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('list_funcionarios')

    @property
    def total_horas_extras(self):
        total = self.registrohoraextra_set.filter(
            utilizada=False).aggregate(
            Sum('horas'))['horas__sum']
        return total or 0

    def __str__(self):
        return self.nome

apps/registro_hora_extra/models.py
from django.db import models
from django.urls import reverse

from apps.funcionarios.models import Funcionario

class RegistroHoraExtra(models.Model):
    motivo = models.CharField(max_length=100)
    funcionario = models.ForeignKey(Funcionario, on_delete=models.PROTECT)
    horas = models.DecimalField(max_digits=5, decimal_places=2)
    utilizada = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('update_funcionario', args=[self.funcionario.id])

    def __str__(self):
        return self.motivo

apps/funcionarios/views.py
import io

from django import template
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from reportlab.pdfgen import canvas

from django.template.loader import get_template
import xhtml2pdf.pisa as pisa


from .models import Funcionario
from .. import funcionarios


class FuncionariosList(ListView):
    model = Funcionario

    def get_queryset(self):
         empressa_logada = self.request.user.funcionario.empresa
         return Funcionario.objects.filter(empresa=empressa_logada)

class FuncionarioEdit(UpdateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

class FuncionarioDelete(DeleteView):
    model = Funcionario
    success_url = reverse_lazy('list_funcionarios')

class FuncionarioNovo(CreateView):
    model = Funcionario
    fields = ['nome', 'departamentos']

    def form_valid(self, form):

        funcionarioObj = form.save(commit=False) # cria o Objeto em memória e não manda pro BD
        username = funcionarioObj.nome.split(' ')[0] + funcionarioObj.nome.split(' ')[1]
        funcionarioObj.empresa = self.request.user.funcionario.empresa
        funcionarioObj.user = User.objects.create(username=username)
        funcionarioObj.save()
        return super(FuncionarioNovo, self).form_valid(form)

def relatorio_funcionarios(request):
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = 'attachment; filename="mypdf.pdf"'  #Content-Disposition ele baixa o arquivo

    buffer = io.BytesIO()
    p = canvas.Canvas(buffer)

    p.drawString(200, 810, 'Relatório de funcionário')

    funcionarios = Funcionario.objects.filter(
        empresa=request.user.funcionario.empresa)

    str_ = 'Nome: %s | Hora Extra %.2f '

    p.drawString(0, 800, '_' * 150)

    y = 750
    for funcionario in funcionarios:
        p.drawString(10, y, str_ % (funcionario.nome, funcionario.total_horas_extras))
        y -= 20

    p.showPage()
    p.save()


    pdf = buffer.getvalue()
    buffer.close()
    response.write(pdf)

    return response

class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(
            io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = 'attachment;filename=%s.pdf' % filename
            return response
        else:
            return HttpResponse("Error Rendering PDF", status=400)

class Pdf(View):

    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',
            'request': request,
        }
        return Render.render('funcionarios/relatorio.html', params, 'myfile')

apps/funcionarios/templates/funcionarios/funcionario_confirm_delete.html
{% extends 'base.html' %}

{% block main %}


<form method="POST">
    {% csrf_token %}
    <h1>Deseja confirmar a Exclusão? {{ usuario.funcionario }} </h1>
    {{ form }}

    <button type="submit" >Confirmar</button>
</form>

{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_form.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block main %}

<h1>{{ object }} </h1>


<form method="POST">
    {% csrf_token %}

    {{ form|bootstrap }}

    <button type="submit" class="btn btn-info">Salvar</button>
</form>

<br>
<h2>Documentos</h2>
<ul>
{% for documento in object.documento_set.all %}

    <li>
        <a href="{{ documento.arquivo.url }}"> {{ documento.descricao }}</a> <br>
    </li>
{% endfor %}
</ul>
{% if object %}
<a href="{% url 'create_documento' object.id %}" class="btn btn-success">
    Adicionar documento
</a>
{% endif %}

<br>
<h2>Banco de Horas</h2>
<ul>
{% for registro_hora in object.registrohoraextra_set.all %}

    <li>
      <a href="{% url 'update_hora_extra' registro_hora.id %}">
          {{ registro_hora.motivo }} | {{ registro_hora.horas }} <br>
      </a>
    </li>
{% endfor %}
</ul>

<h3> Total de horas extras: {{ object.total_horas_extras }} </h3>
{% endblock %}

apps/funcionarios/templates/funcionarios/funcionario_list.html
{% extends 'base.html' %}

{% block main %}

    <h2 class="mt-4 mb-4 border-bottom pb-2">Lista de Funcionários </h2>
<br>


<table class="table">
  <thead>
    <tr>
      <th scope="col">Editar Funcionario</th>
      <th scope="col">Ação</th>
    </tr>
  </thead>
  <tbody>
        {% for funcionario in object_list %}
    <tr>

      <td class="table-primary">
          <a class="btn btn-light" href="{% url 'update_funcionario'  funcionario.id %}"
           role="button"> {{ funcionario }}  </a>
      </td>
      <td class="table-primary">
          <a href="{% url 'delete_fucionario' funcionario.id %}" class="btn btn-danger">Deletar </a>

      </td>
    </tr>

        {%endfor%}
  </tbody>
</table>





<a href=" {% url 'create_funcionario' %}" class="btn btn-primary"> Novo</a>
<a href="{% url 'relatorio_funcionarios' %}" class="btn btn-primary"> Gerar PDF relatório de funcionarios</a>
<a href="{% url 'relatorio_funcionarios_html' %}" class="btn btn-primary"> Relatório de funcionarios HTML</a>

{% endblock %}

apps/funcionarios/templates/funcionarios/relatorio.html
{% extends 'base.html' %}


{% block main %}
    <h1>Meu relatorio</h1>
    <h2> {{ sales }}</h2>
{% endblock %}